# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    Lettore:
                        password: $2y$12$bNNrmehkTd1qRnGERP85/uu9mOIapR62Oy7s7p/w/.tvszieffLM6 
                        roles: 'ROLE_USER'

    encoders:
         Symfony\Component\Security\Core\User\User:
              algorithm: bcrypt
              cost: 12

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~            
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path:   /logout
                target: /
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
