# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
 paulp_jackontour_tappetype:
  class: Paulp\JackontourBundle\Form\TappeType
  arguments: 
   - "@paulp_jackontour_googleapi"
   
 paulp_jackontour_googleapi:
  class: Paulp\JackontourBundle\Service\Googleapi
  arguments: ["%googlekey%"]
  
 paulp_jackontour_instaapi:
  class: Paulp\JackontourBundle\Service\Instaapi
  arguments: ["%client_id%", "%client_secret%"]
  
